# Generated by Django 3.1.3 on 2020-11-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='img',
            field=models.ImageField(default='demo.png', upload_to='propertypic'),
        ),
    ]
